(0009,0010) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="?"				Name="?"
(0009,0011) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="?"				Name="?"
(0009,0013) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="?"				Name="?"
(0009,0014) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="?"				Name="?"
(0009,0015) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="?"				Name="?"

(0011,0020) VERS="AGFA"	VR="LO"   VM="1"	Owner="AgilityRuntime"		Keyword="?"				Name="?"
(0011,0021) VERS="AGFA"	VR="LO"   VM="1"	Owner="AgilityRuntime"		Keyword="?"				Name="?"
(0011,0022) VERS="AGFA"	VR="LO"   VM="1"	Owner="AgilityRuntime"		Keyword="?"				Name="?"

(0011,0011) VERS="AGFA"	VR="SH"   VM="1"	Owner="AGFA-AG_HPState"		Keyword="?"				Name="?"

(0019,00a0) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AGFA-AG_HPState"		Keyword="?"				Name="?"
(0019,00a1) VERS="AGFA"	VR="FL"   VM="1"	Owner="AGFA-AG_HPState"		Keyword="?"				Name="?"
(0019,00a2) VERS="AGFA"	VR="FL"   VM="1"	Owner="AGFA-AG_HPState"		Keyword="?"				Name="?"
(0019,00a3) VERS="AGFA"	VR="FL"   VM="1"	Owner="AGFA-AG_HPState"		Keyword="?"				Name="?"
(0019,00a4) VERS="AGFA"	VR="FL"   VM="1"	Owner="AGFA-AG_HPState"		Keyword="?"				Name="?"

(0019,0005) VERS="AGFA"	VR="ST"   VM="1"	Owner="AGFA"		Keyword="CassetteDataStream"					Name="Cassette Data Stream"
(0019,0010) VERS="AGFA"	VR="ST"   VM="1"	Owner="AGFA"		Keyword="ImageProcessingParameters"				Name="Image Processing Parameters"
(0019,0011) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="IdentificationData"					Name="Identification Data"
(0019,0013) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="SensitometryName"						Name="Sensitometry Name"
(0019,0014) VERS="AGFA"	VR="ST"   VM="1"	Owner="AGFA"		Keyword="WindowLevelList"						Name="Window Level List"
(0019,0015) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="DoseMonitoring"						Name="Dose Monitoring"
(0019,0016) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="OtherInfo"								Name="Other Info"
(0019,001a) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="ClippedExposureDeviation"				Name="Clipped Exposure Deviation"
(0019,001b) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA"		Keyword="Logarithmic PLT Full Scale"			Name="Logarithmic PLT Full Scale"
(0019,0060) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA"		Keyword="TotalNumberSeries"						Name="Total Number Series"
(0019,0061) VERS="AGFA"	VR="SH"   VM="1"	Owner="AGFA"		Keyword="SessionNumber"							Name="Session Number"
(0019,0062) VERS="AGFA"	VR="SH"   VM="1"	Owner="AGFA"		Keyword="IDStationName"							Name="ID Station Name"
(0019,0065) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA"		Keyword="NumberOfImagesInStudyToBeTransmitted"	Name="Number of Images in Study to be Transmitted"
(0019,0070) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA"		Keyword="TotalNumberImages"						Name="Total Number Images"
(0019,0080) VERS="AGFA"	VR="ST"   VM="1"	Owner="AGFA"		Keyword="GeometricalTransformations"			Name="Geometrical Transformations"
(0019,0081) VERS="AGFA"	VR="ST"   VM="1"	Owner="AGFA"		Keyword="RoamOrigin"							Name="Roam Origin"
(0019,0082) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA"		Keyword="ZoomFactor"							Name="Zoom Factor"
(0019,0093) VERS="AGFA"	VR="CS"   VM="1"	Owner="AGFA"		Keyword="Status"								Name="Status"

(0019,0030) VERS="AGFA"	VR="ST"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="DataStreamFromCassette"	Name="Data stream from cassette"
(0019,0030) VERS="AGFA"	VR="ST"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="SetOfDestinationTypes"		Name="Set of destination types"
(0019,0040) VERS="AGFA"	VR="ST"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="SetOfDestinationIds"		Name="Set of destination Ids"
(0019,0050) VERS="AGFA"	VR="ST"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="SetOfProcessingCodes"		Name="Set of processing codes"
(0019,0060) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="NumberOfSeriesInStudy"		Name="Number of series in study"
(0019,0061) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="SessionNumber"			Name="Session Number"
(0019,0062) VERS="AGFA"	VR="SH"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="IDStationName"			Name="ID station name"
(0019,0070) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="NumberOfImagesInSeries"	Name="Number of images in series"
(0019,0071) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="BreakCondition"		Name="Break condition"
(0019,0072) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="WaitOrHoldFlag"		Name="Wait (or Hold) flag"
(0019,0073) VERS="AGFA"	VR="US"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="ScanResFlag"			Name="ScanRes flag"
(0019,0074) VERS="AGFA"	VR="SH"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="OperationCode"			Name="Operation code"
(0019,0095) VERS="AGFA"	VR="CS"   VM="1"	Owner="AGFA_ADC_Compact"	Keyword="ImageQuality"			Name="Image quality"

(0019,0007) VERS="AGFA"	VR="CS"   VM="1"	Owner="Agfa ADC NX"	Keyword="?"	Name="?"
(0019,0009) VERS="AGFA"	VR="SQ"   VM="1"	Owner="Agfa ADC NX"	Keyword="?"	Name="?"
(0019,0021) VERS="AGFA"	VR="FL"   VM="1"	Owner="Agfa ADC NX"	Keyword="?"	Name="?"
(0019,0028) VERS="AGFA"	VR="CS"   VM="1"	Owner="Agfa ADC NX"	Keyword="?"	Name="?"
(0019,00f0) VERS="AGFA"	VR="LO"   VM="1"	Owner="Agfa ADC NX"	Keyword="UserDefinedField1"	Name="User Defined field 1"
(0019,00f1) VERS="AGFA"	VR="LO"   VM="1"	Owner="Agfa ADC NX"	Keyword="UserDefinedField2"	Name="User Defined field 2"
(0019,00f2) VERS="AGFA"	VR="LO"   VM="1"	Owner="Agfa ADC NX"	Keyword="UserDefinedField3"	Name="User Defined field 3"
(0019,00f3) VERS="AGFA"	VR="LO"   VM="1"	Owner="Agfa ADC NX"	Keyword="UserDefinedField4"	Name="User Defined field 4"
(0019,00f4) VERS="AGFA"	VR="LO"   VM="1"	Owner="Agfa ADC NX"	Keyword="UserDefinedField5"	Name="User Defined field 5"
(0019,00f5) VERS="AGFA"	VR="CS"   VM="1"	Owner="Agfa ADC NX"	Keyword="CassetteOrientation"	Name="Cassette Orientation"
(0019,00f6) VERS="AGFA"	VR="DS"   VM="1"	Owner="Agfa ADC NX"	Keyword="PlateSensitivity"	Name="Plate Sensitivity"
(0019,00f7) VERS="AGFA"	VR="DS"   VM="1"	Owner="Agfa ADC NX"	Keyword="PlateErasability"	Name="Plate Erasability"
(0019,00f8) VERS="AGFA"	VR="IS"   VM="1"	Owner="Agfa ADC NX"	Keyword="?"	Name="?"
(0019,00fa) VERS="AGFA"	VR="IS"   VM="1"	Owner="Agfa ADC NX"	Keyword="?"	Name="?"
(0019,00fc) VERS="AGFA"	VR="IS"   VM="1"	Owner="Agfa ADC NX"	Keyword="?"	Name="?"
(0019,00fd) VERS="AGFA"	VR="CS"   VM="1"	Owner="Agfa ADC NX"	Keyword="?"	Name="?"
(0019,00fe) VERS="AGFA"	VR="CS"   VM="1"	Owner="Agfa ADC NX"	Keyword="?"	Name="?"

(0031,0000) VERS="MIT"  VR="CS"   VM="1"	Owner="AGFA PACS Archive Mirroring 1.0"	Keyword="?"		Name="?"
(0031,0001) VERS="MIT"  VR="UL"   VM="1"	Owner="AGFA PACS Archive Mirroring 1.0"	Keyword="?"		Name="?"

(0029,0000) VERS="MIT"  VR="CS"   VM="1"	Owner="MITRA PRESENTATION 1.0"	Keyword="Rotation"			Name="Rotation"
(0029,0001) VERS="MIT"  VR="LO"   VM="1"	Owner="MITRA PRESENTATION 1.0"	Keyword="WindowWidth"		Name="Window Width"
(0029,0002) VERS="MIT"  VR="LO"   VM="1"	Owner="MITRA PRESENTATION 1.0"	Keyword="WindowCentre"		Name="Window Centre"
(0029,0003) VERS="MIT"  VR="IS"   VM="1"	Owner="MITRA PRESENTATION 1.0"	Keyword="Invert"			Name="Invert"
(0029,0004) VERS="MIT"  VR="IS"   VM="1"	Owner="MITRA PRESENTATION 1.0"	Keyword="HasTabstop"		Name="Has Tabstop"
(0029,0005) VERS="MIT"  VR="CS"   VM="1"	Owner="MITRA PRESENTATION 1.0"	Keyword="SmoothRotation"	Name="Smooth Rotation"
(0029,0010) VERS="MIT"  VR="CS"   VM="1"	Owner="MITRA PRESENTATION 1.0"	Keyword="?"		Name="?"
(0029,0011) VERS="MIT"  VR="CS"   VM="1"	Owner="MITRA PRESENTATION 1.0"	Keyword="?"		Name="?"
(0029,0012) VERS="MIT"  VR="CS"   VM="1"	Owner="MITRA PRESENTATION 1.0"	Keyword="?"		Name="?"
(0029,0013) VERS="MIT"  VR="CS"   VM="1"	Owner="MITRA PRESENTATION 1.0"	Keyword="?"		Name="?"

(0029,0000) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT DOCUMENT 1.0"	Keyword="IMPAXObjectDocument"		Name="IMPAX Object Document"	RenderAsString="true"
(0029,0001) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT DOCUMENT 1.0"	Keyword="IMPAXMarkupXMLStored"		Name="IMPAX Markup XML Stored"	RenderAsString="true"

(0029,0000) VERS="MIT"  VR="OB"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="Markup1"		Name="Markup1"	RenderAsString="true"
(0029,0001) VERS="MIT"  VR="OB"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="Markup2"		Name="Markup2"	RenderAsString="true"
(0029,0002) VERS="MIT"  VR="OB"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="Markup3"		Name="Markup3"	RenderAsString="true"
(0029,0003) VERS="MIT"  VR="OB"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="Markup4"		Name="Markup4"	RenderAsString="true"
(0029,0004) VERS="MIT"  VR="OB"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="Markup5"		Name="Markup5"	RenderAsString="true"
(0029,0005) VERS="MIT"  VR="OB"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="Markup6"		Name="Markup6"	RenderAsString="true"
(0029,0006) VERS="MIT"  VR="OB"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="Markup7"		Name="Markup7"	RenderAsString="true"
(0029,0007) VERS="MIT"  VR="OB"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="Markup8"		Name="Markup8"	RenderAsString="true"
(0029,0008) VERS="MIT"  VR="OB"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="Markup9"		Name="Markup9"	RenderAsString="true"
(0029,0009) VERS="MIT"  VR="OB"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="Markup10"		Name="Markup10"	RenderAsString="true"
(0029,0010) VERS="MIT"  VR="OB"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="Markup11"		Name="Markup11"	RenderAsString="true"
(0029,0011) VERS="MIT"  VR="OB"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="Markup12"		Name="Markup12"	RenderAsString="true"
(0029,0012) VERS="MIT"  VR="OB"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="Markup13"		Name="Markup13"	RenderAsString="true"
(0029,0013) VERS="MIT"  VR="OB"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="Markup14"		Name="Markup14"	RenderAsString="true"
(0029,0014) VERS="MIT"  VR="OB"   VM="1-n"	Owner="MITRA MARKUP 1.0"	Keyword="Markup15"		Name="Markup14"	RenderAsString="true"

(0029,0011) VERS="AGFA"    VR="CS"   VM="1"	Owner="AgilityRuntime"			Keyword="?"							Name="?"
(0029,0012) VERS="AGFA"    VR="US"   VM="1"	Owner="AgilityRuntime"			Keyword="?"							Name="?"
(0029,0013) VERS="AGFA"    VR="US"   VM="1"	Owner="AgilityRuntime"			Keyword="?"							Name="?"
(0029,0014) VERS="AGFA"    VR="US"   VM="1"	Owner="AgilityRuntime"			Keyword="?"							Name="?"
(0029,001f) VERS="AGFA"    VR="US"   VM="1"	Owner="AgilityRuntime"			Keyword="?"							Name="?"

(0029,001f) VERS="AGFA"	VR="US"   VM="1"	Owner="AgilityRuntime"		Keyword="?"				Name="?"

(0031,0020) VERS="MIT"  VR="IS"   VM="1"	Owner="MITRA LINKED ATTRIBUTES 1.0"	Keyword="?"		Name="?"

(0033,0002) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0004) VERS="MIT"  VR="CS"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0006) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0008) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,000a) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,000c) VERS="MIT"  VR="LO"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,000e) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0013) VERS="MIT"  VR="PN"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0014) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0015) VERS="MIT"  VR="OB"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0016) VERS="MIT"  VR="PN"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0019) VERS="MIT"  VR="PN"   VM="1"	Owner="MITRA OBJECT UTF8 ATTRIBUTES 1.0"	Keyword="?"		Name="?"

(0033,0002) VERS="MIT"  VR="LO"   VM="1"	Owner="MITRA OBJECT ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0004) VERS="MIT"  VR="LO"   VM="1"	Owner="MITRA OBJECT ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0006) VERS="MIT"  VR="LO"   VM="1"	Owner="MITRA OBJECT ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,0008) VERS="MIT"  VR="LO"   VM="1"	Owner="MITRA OBJECT ATTRIBUTES 1.0"	Keyword="?"		Name="?"
(0033,000a) VERS="MIT"  VR="LO"   VM="1"	Owner="MITRA OBJECT ATTRIBUTES 1.0"	Keyword="?"		Name="?"

(0071,0018) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,0019) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,001a) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,001c) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,001e) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,0020) VERS="AGFA"	VR="FL"   VM="1-n"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,0021) VERS="AGFA"	VR="FD"   VM="1-n"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,0022) VERS="AGFA"	VR="FD"   VM="1-n"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,0023) VERS="AGFA"	VR="FD"   VM="1-n"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,0024) VERS="AGFA"	VR="FD"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,002b) VERS="AGFA"	VR="FD"   VM="1-n"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,002c) VERS="AGFA"	VR="FD"   VM="3"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0071,002d) VERS="AGFA"	VR="FD"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"

(0071,0001) VERS="AGFA"	VR="ST"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0002) VERS="AGFA"	VR="ST"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0003) VERS="AGFA"	VR="ST"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0005) VERS="AGFA"	VR="ST"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0006) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0007) VERS="AGFA"	VR="ST"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0008) VERS="AGFA"	VR="CS"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0009) VERS="AGFA"	VR="ST"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,000a) VERS="AGFA"	VR="CS"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0010) VERS="AGFA"	VR="FL"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0011) VERS="AGFA"	VR="ST"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0012) VERS="AGFA"	VR="CS"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0013) VERS="AGFA"	VR="US"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0014) VERS="AGFA"	VR="US"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0015) VERS="AGFA"	VR="FD"   VM="1-n"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0016) VERS="AGFA"	VR="ST"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0017) VERS="AGFA"	VR="ST"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0018) VERS="AGFA"	VR="CS"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0019) VERS="AGFA"	VR="ST"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,001b) VERS="AGFA"	VR="ST"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,001c) VERS="AGFA"	VR="ST"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,001d) VERS="AGFA"	VR="ST"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0022) VERS="AGFA"	VR="ST"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,002c) VERS="AGFA"	VR="ST"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,002d) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,002e) VERS="AGFA"	VR="US"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0050) VERS="AGFA"	VR="CS"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0051) VERS="AGFA"	VR="CS"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0052) VERS="AGFA"	VR="LT"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0053) VERS="AGFA"	VR="CS"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0054) VERS="AGFA"	VR="CS"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0055) VERS="AGFA"	VR="CS"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0056) VERS="AGFA"	VR="CS"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0057) VERS="AGFA"	VR="CS"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0059) VERS="AGFA"	VR="FL"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,005a) VERS="AGFA"	VR="FL"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,005b) VERS="AGFA"	VR="FL"   VM="2"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,005c) VERS="AGFA"	VR="FL"   VM="4"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,005d) VERS="AGFA"	VR="CS"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"
(0071,0060) VERS="AGFA"	VR="FD"   VM="1"	Owner="AgilityOverlay"	Keyword="?"		Name="?"

(0073,0023) VERS="AGFA"	VR="SH"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0073,0024) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0073,0028) VERS="AGFA"	VR="SQ"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0073,0080) VERS="AGFA"	VR="FL"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"

(0075,0010) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"

(0087,0001) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0087,0002) VERS="AGFA"	VR="LO"   VM="1"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0087,0003) VERS="AGFA"	VR="SL"   VM="2"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0087,0004) VERS="AGFA"	VR="SL"   VM="2"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0087,0005) VERS="AGFA"	VR="FD"   VM="2"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0087,0006) VERS="AGFA"	VR="FD"   VM="2"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0087,0007) VERS="AGFA"	VR="FD"   VM="2"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"
(0087,0008) VERS="AGFA"	VR="FD"   VM="2"	Owner="AGFA-AG_HPState"	Keyword="?"		Name="?"

(0035,0000) VERS="AGFA"	VR="SH"   VM="1"	Owner="AGFA KOSD 1.0"	Keyword="?"		Name="?"
(0035,0003) VERS="AGFA"	VR="LT"   VM="1"	Owner="AGFA KOSD 1.0"	Keyword="?"		Name="?"

(2e13,0010) VERS="AGFA"	VR="IS"   VM="1"	Owner="agfa/displayableImages"	Keyword="?"		Name="?"
(2e13,0011) VERS="AGFA"	VR="IS"   VM="1"	Owner="agfa/displayableImages"	Keyword="?"		Name="?"

(7fdb,0099) VERS="AGFA"	VR="LO"   VM="1"	Owner="agfa/xeroverse"	Keyword="?"		Name="?"

